#!/bin/bash

# Cores

COR[0]="\[\033[0m\]" # Normal
COR[1]="\[\033[1;31m\]" # Vermelho
COR[2]="\[\033[1;32m\]" # Verde
COR[3]="\[\033[1;33m\]" # Amarelo
COR[4]="\[\033[1;34m\]" # Azul
COR[5]="\[\033[1;35m\]" # Roxo
COR[6]="\[\033[1;36m\]" # Cian
COR[7]="\[\033[1;37m\]" # Branco
COR[8]="\[\033[01;96m\]" # Azul Claro

DES[0]="\342\224\214\342\224\200" # Linha de canto
DES[1]="\342\224\224\342\224\200\342\224\200\342\225\274" # Linha e ponto
DES[2]="\342\234\227" # Sinal de erro
DES[3]="\342\224\200" # Linha horizontal


# Partes

USER="${COR[0]}\u"
SERVER="${COR[6]}\h"
DIR="${COR[2]}\w"
SEPARADOR="${COR[5]}${DES[3]}"
ANTES="${COR[5]}${DES[0]}"
DEPOIS="\n${COR[5]}${DES[1]}"
HORARIO="${COR[7]}\t"
CURSOR="${COR[1]} \$ "
MSG="${COR[3]}[${COR[1]}${DES[2]}${COR[3]}]${COR[5]}${DES[3]}"

ERRO='$([[ $? != 0 ]] && echo "'${MSG}'")'

PS1="${ANTES}${ERRO}${COR[7]}[${USER}${COR[3]}@${SERVER}${COR[7]}]${SEPARADOR}${COR[7]}[${DIR}${COR[7]}]${COR[3]}(${HORARIO}${COR[3]})${DEPOIS}${CURSOR}${COR[0]}"

