#!/bin/bash

# Cores

COR[0]="\[\e[0m\]" # Normal
COR[1]="\[\e[1;31m\]" # Vermelho
COR[2]="\[\e[1;32m\]" # Verde
COR[3]="\[\e[1;33m\]" # Amarelo
COR[4]="\[\e[1;34m\]" # Azul
COR[5]="\[\e[1;35m\]" # Roxo
COR[6]="\[\e[1;36m\]" # Cian
COR[7]="\[\e[1;37m\]" # Branco
COR[8]="\[\e[1;96m\]" # Azul Claro

DES[0]="\342\224\214\342\224\200" # Linha de canto
DES[1]="\342\224\224\342\224\200\342\224\200\342\225\274" # Linha e ponto
DES[2]="\342\234\227" # Sinal de erro
DES[3]="\342\224\200" # Linha horizontal


# Partes

ANTES="${COR[5]}${DES[0]}"

MSG="${COR[3]}[${COR[1]}${DES[2]}${COR[3]}]${COR[5]}${DES[3]}"
ERRO='$([[ $? != 0 ]] && echo "'${MSG}'")'

USER="${COR[8]}\u"
SERVER="${COR[4]}\h"
SEPARADOR="${COR[5]}${DES[3]}"
DIR="${COR[2]}\w"
HORARIO="${COR[7]}\t"

DEPOIS="\n${COR[5]}${DES[1]}"
CURSOR="${COR[1]} \$ "

PS1="${ANTES}${ERRO}${COR[7]}[${USER}${COR[3]}@${SERVER}${COR[7]}]${SEPARADOR}${COR[7]}[${DIR}${COR[7]}]${COR[3]}(${HORARIO}${COR[3]})${DEPOIS}${CURSOR}${COR[0]}"

echo "Colocar no .bashrc:"
echo
echo 'PS1="'$PS1'"'
echo
